site_name: CS Cloud Wiki
strict: false

nav:
    - 简介: index.md
    - Leetcode:
          - leetcode: leetcode/new/leetcode.md
          - 集合中的元素: leetcode/new/集合中的元素.md
          - 栈: leetcode/new/栈.md
          - 树: leetcode/new/树.md
          - 区间: leetcode/new/区间.md
          - 找数: leetcode/new/找数.md
          - 排序: leetcode/new/排序.md
          - 搜索: leetcode/new/搜索.md
          - 数组: leetcode/new/数组.md
          - 数论: leetcode/new/数论.md
          - 构造: leetcode/new/构造.md
          - 柱子: leetcode/new/柱子.md
          - 矩阵: leetcode/new/矩阵.md
          - 组合: leetcode/new/组合.md
          - 结构: leetcode/new/结构.md
          - 链表: leetcode/new/链表.md
          - 中位数: leetcode/new/中位数.md
          - 位运算: leetcode/new/位运算.md
          - 可达性: leetcode/new/可达性.md
          - 子序列: leetcode/new/子序列.md
          - 字典序: leetcode/new/字典序.md
          - 最大序: leetcode/new/最大序.md
          - 前缀树Trie: leetcode/new/前缀树Trie.md
          - 二分查找: leetcode/new/二分查找.md
          - 拓扑排序: leetcode/new/拓扑排序.md
          - 最长子串: leetcode/new/最长子串.md
          - 二分猜答案: leetcode/new/二分猜答案.md
          - 多少种不同: leetcode/new/多少种不同.md
          - 子数组子串: leetcode/new/子数组子串.md
          - 字符串匹配: leetcode/new/字符串匹配.md
          - 字符串编辑: leetcode/new/字符串编辑.md
          - 最长公共前缀: leetcode/new/最长公共前缀.md
          - 多步操作最优解: leetcode/new/多步操作最优解.md
          - 多线程: leetcode/new/多线程.md
    - Java:
          - JDK: java/JDK下载.md
          - HashMap: java/HashMap.md
          - Map-API: java/Map-API.md

theme:
    name: material # 可选项还有些别的, material star 遥遥领先
    font:
        code: Fira Code
        text: Inter
    features:
        - toc.follow # Table of contents 跟着滚
        - content.tabs.link
        - content.code.copy # 控制代码块的复制按钮
        - navigation.instant # 即时加载 XHR
        - navigation.tabs # 导航卡横向
        - navigation.top # goto top
    palette:
        # Palette toggle for light mode
        - scheme: default
          media: "(prefers-color-scheme: light)"
          primary: black
          accent: orange
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          media: "(prefers-color-scheme: dark)"
          primary: black
          accent: orange
          toggle:
              icon: material/weather-night
              name: Switch to light mode
markdown_extensions:
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true # 切换代码块所必需的
    - pymdownx.highlight:
          use_pygments: true # pygments的style虽然不够丰富, 但是高亮不错
          pygments_lang_class: true # 语言识别?
          noclasses: true # 必须启用style才生效
          pygments_style: "dracula"
          # linenums: true
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
    - javascripts/katex.js
#    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
#    - javascripts/highlight.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
    - stylesheets/extra.css
#    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/androidstudio.min.css
#    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/stackoverflow-light.min.css
#    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-light.min.css
#    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css
